version: 1.0.{build}

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk17

install:
  - ps: |
      $androidHome = "C:\android-sdk"
      $env:ANDROID_SDK_ROOT = $androidHome
      $env:ANDROID_HOME = $androidHome

build_script:
  - gradlew assembleDebug

artifacts:
  - path: app\build\outputs\apk\debug\app-debug.apk
    name: MockLocationApp
